[package]
name = "brain-dock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
brain-proto = { workspace = true }
brain-x11 = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
slint = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
raw-window-handle = "0.6"
uuid = { version = "1", features = ["v4"] }
arboard = "3"

[build-dependencies]
slint-build = { workspace = true }
